### ISSUE TITLE
Change Default Clear Output to False

### ISSUE THREAD

**Issue by kishansairam9** [KwatME/clean_ipynb#11]
@KwatME Most of the people who might want to use this tool actually are interested in formatting the python code aspects. Clearing the output might not be of their interest since once they push their code to repo / share their code somewhere they want to show their results too (i.e, plots or output's like accuracy etc.). Thus I think default should be not clearing output & clearing output can be enabled through flag

**Comment by kishansairam9** [comment]
Also please delete line 62: (- And the) in README.md. I m sorry for the overlook

**Comment by KwatME** [comment]
Agreed. Let's do it.
