### ISSUE TITLE
Shell Commands with ! causing program to crash

### ISSUE THREAD

**Issue by kishansairam9** [KwatME/clean_ipynb#13]
<img width="682" alt="Screen Shot 2019-07-10 at 11 53 38 AM" src="https://user-images.githubusercontent.com/40003481/60945598-a3d21c80-a309-11e9-9769-23254b46d572.png">

**Comment by KwatME** [comment]
Got it - thanks.

**Comment by kishansairam9** [comment]
I sent a pr to fix it and some other changes https://github.com/KwatME/clean_ipynb/pull/16
