### ISSUE TITLE
Add topics to the repo

### ISSUE THREAD

**Issue by homocomputeris** [KwatME/clean_ipynb#26]
[Topics](https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics) help to discover interesting packages. As an example, [jupyter](https://github.com/topics/jupyter).

**Comment by KwatME** [comment]
Sounds good. Could you recommend which topics to add? Let's add jupyter, python, julia, and clean as a start.

**Comment by KwatME** [comment]
This issue is closed but feel free to comment your recommendation to add. Thanks!

**Comment by homocomputeris** [comment]
Thanks. `jupyter-notebook ipynb`, for example. Also, each topic's page shows related ones on the right.
