### ISSUE TITLE
Speed up cleaning julia notebook

### ISSUE THREAD

**Issue by homocomputeris** [KwatME/clean_ipynb#27]
Maybe, it is supposed to be so but it takes 2 minutes to clean a notebook with 5 non-empty Julia cells (and any other except an empty one)
```console
$ time clean_ipynb 5\ Conditionals\ and\ Recursion.ipynb
5 Conditionals and Recursion.ipynb
clean_ipynb 5\ Conditionals\ and\ Recursion.ipynb  131,02s user 1,03s system 99% cpu 2:12,97 total
```
Version info:

- clean_ipynb master branch
- python-black 19.3b0-2
- python-isort 4.3.21.2-1
- julia 1.2.0
- JuliaFormatter v0.1.19

**Comment by KwatME** [comment]
Thanks for the information. I'm going to investigate this.

**Comment by KwatME** [comment]
Cleaning julia notebook is slow because each cell requires an initialization of julia. I'm going to find a way to initialize julia once per notebook (or less).
