### ISSUE TITLE
Add option to fail if dirty

### ISSUE THREAD

**Issue by tibdex** [KwatME/clean_ipynb#30]
It would be good to add an option to exit with an error code if some cleaning was needed. A bit like Prettier's [`--check` option](https://prettier.io/docs/en/cli.html#check).

Thanks ;)

**Comment by KwatME** [comment]
Sounds good. Thank you for the input @tibdex

**Comment by KwatME** [comment]
I made the error message better. It should be easy to see if there is any failure.

I tried to add --check option but the code base size increased more than 30%. For keeping this took as simple as possible, I hope the improved error message would be enough to inform a user about the notebook statuses.

If you still needed the check option, I'm happy to add it back.
