### ISSUE TITLE
Implement a progress bar for huge notebooks

### ISSUE THREAD

**Issue by dan-r95** [KwatME/clean_ipynb#36]
In my opinion a progressbar like would be desirable to ensure the user nothing has crashed yet
![image](https://user-images.githubusercontent.com/18677643/98109746-5aaec000-1e9e-11eb-813a-b30ef918359d.png)

A sample implementation
[can be found here](https://gist.github.com/vladignatyev/06860ec2040cb497f0f3)

**Comment by KwatME** [comment]
Let's do this!

**Comment by KwatME** [comment]
@dan-r95 , do you still need this? For keeping the code base size as small and the tool as light as possible, maybe we can skip this? Please let me know (feel free to reopen the issue).
